# 어플리케이션 포트 -> 디폴트가 8080
server:
  port: 8080

# database 연동 설정
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/juhye?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: juhye
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 정적 파일 서버 재실행 없이 새로고침으로 반영
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
